### ISSUE TITLE
flaky test in controllers/thread

### ISSUE THREAD

**Issue by unenglishable** [epochtalk/epochtalk_server#63]
1) test by_board/2 given an id for board above authenticated user priority, does not get threads (Test.EpochtalkServerWeb.Controllers.Thread)
Error:      test/epochtalk_server_web/controllers/thread_test.exs:120
     ** (KeyError) key :permissions not found in: %{}
     code: |> get(Routes.thread_path(conn, :by_board), %{board_id: super_admin_board.id})
     stacktrace:
       (epochtalk_server 0.1.0) lib/epochtalk_server/models/role.ex:291: EpochtalkServer.Models.Role.get_masked_permissions/1
       (epochtalk_server 0.1.0) lib/epochtalk_server_web/helpers/acl.ex:144: EpochtalkServerWeb.Helpers.ACL.get_user_priority/1
       (epochtalk_server 0.1.0) lib/epochtalk_server_web/controllers/thread.ex:70: EpochtalkServerWeb.Controllers.Thread.by_board/2
       (epochtalk_server 0.1.0) lib/epochtalk_server_web/controllers/thread.ex:1: EpochtalkServerWeb.Controllers.Thread.action/2
       (epochtalk_server 0.1.0) lib/epochtalk_server_web/controllers/thread.ex:1: EpochtalkServerWeb.Controllers.Thread.phoenix_controller_pipeline/2
       (phoenix 1.7.2) lib/phoenix/router.ex:430: Phoenix.Router.__call__/5
       (epochtalk_server 0.1.0) lib/epochtalk_server_web/endpoint.ex:1: EpochtalkServerWeb.Endpoint.plug_builder_call/2
       (epochtalk_server 0.1.0) lib/epochtalk_server_web/endpoint.ex:1: EpochtalkServerWeb.Endpoint.call/2
       (phoenix 1.7.2) lib/phoenix/test/conn_test.ex:225: Phoenix.ConnTest.dispatch/5
       test/epochtalk_server_web/controllers/thread_test.exs:132: (test)

**Comment by akinsey** [comment]
```
 1) test by_board/2 given an id for board above authenticated user priority, does not get threads (Test.EpochtalkServerWeb.Controllers.Thread)
     test/epochtalk_server_web/controllers/thread_test.exs:120
     ** (KeyError) key :permissions not found in: %{}
     code: |> get(Routes.thread_path(conn, :by_board), %{board_id: admin_board.id})
     stacktrace:
       (epochtalk_server 0.1.0) lib/epochtalk_server/models/role.ex:291: EpochtalkServer.Models.Role.get_masked_permissions/1
       (epochtalk_server 0.1.0) lib/epochtalk_server_web/helpers/acl.ex:147: EpochtalkServerWeb.Helpers.ACL.get_user_priority/1
       (epochtalk_server 0.1.0) lib/epochtalk_server_web/controllers/thread.ex:172: EpochtalkServerWeb.Controllers.Thread.by_board/2
       (epochtalk_server 0.1.0) lib/epochtalk_server_web/controllers/thread.ex:1: EpochtalkServerWeb.Controllers.Thread.action/2
       (epochtalk_server 0.1.0) lib/epochtalk_server_web/controllers/thread.ex:1: EpochtalkServerWeb.Controllers.Thread.phoenix_controller_pipeline/2
       (phoenix 1.7.2) lib/phoenix/router.ex:430: Phoenix.Router.__call__/5
       (epochtalk_server 0.1.0) lib/epochtalk_server_web/endpoint.ex:1: EpochtalkServerWeb.Endpoint.plug_builder_call/2
       (epochtalk_server 0.1.0) lib/epochtalk_server_web/endpoint.ex:1: EpochtalkServerWeb.Endpoint.call/2
       (phoenix 1.7.2) lib/phoenix/test/conn_test.ex:225: Phoenix.ConnTest.dispatch/5
       test/epochtalk_server_web/controllers/thread_test.exs:127: (test)

```
