### ISSUE TITLE
flaky test in controllers/notification

### ISSUE THREAD

**Issue by unenglishable** [epochtalk/epochtalk_server#86]
1) test counts/2 when authenticated as notification receiver and notifications exceed default max, returns max+ (Test.EpochtalkServerWeb.Controllers.Notification)
Error:      test/epochtalk_server_web/controllers/notification_test.exs:67
     ** (KeyError) key :id not found in: false. If you are using the dot syntax, such as map.field, make sure the left-hand side of the dot is a map
     stacktrace:
       (epochtalk_server 0.1.0) test/support/factory.ex:15: Test.Support.Factory.mention_factory/1
       (elixir 1.14.4) lib/stream.ex:1559: Stream.do_repeatedly/3
       (elixir 1.14.4) lib/enum.ex:3448: Enum.take/2
       test/epochtalk_server_web/controllers/notification_test.exs:21: Test.EpochtalkServerWeb.Controllers.Notification.__ex_unit_setup_1/1
       test/epochtalk_server_web/controllers/notification_test.exs:1: Test.EpochtalkServerWeb.Controllers.Notification.__ex_unit__/2

**Comment by akinsey** [comment]
This should be resolved after merging in `move-thread`
